# Generated by Django 4.2 on 2026-03-26 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=15, null=True, unique=True)),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('recruiter', 'Recruiter'), ('candidate', 'Candidate')], default='candidate', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_active', 'In Active')], default='active', max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customusermodel',
            constraint=models.UniqueConstraint(fields=('email', 'role'), name='unique_email_role'),
        ),
    ]
